# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\20211126110405145.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT20211126110405145(HttpRunner):

    config = (
        Config("test2")
        .variables(**{"foo1": "test1", "foo2": "test2", "sum_v": "${sum_two(1, 2)}"})
        .base_url("https://postman-echo.com")
        .verify(False)
        .export(*[])
    )

    teststeps = [
        Step(
            RunRequest("get with params")
            .with_variables(**{})
            .get("/get")
            .with_params(**{"foo1": "$foo1", "foo3": "test1"})
            .with_headers(**{"content_type": "application/x-www-form-urlencoded"})
            .extract()
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseT20211126110405145().test_start()
