# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\634.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT634(HttpRunner):

    config = (
        Config("获取公共token	,手机号为空")
        .variables(
            **{
                "clientType": "mch",
                "faccType": "1",
                "fmchid": "10131",
                "forderType": "4",
                "fuid": "200000433",
                "phone": "098630001",
                "toFuid": "10131",
            }
        )
        .base_url("http://192.168.50.34:18081")
        .verify(False)
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("获取公共token")
            .with_variables(**{})
            .post("/api/public/token/getSignToken")
            .with_params(
                **{
                    "clientType": "$clientType",
                    "phone": "",
                    "timeStamp": "${get_timestamp()}",
                }
            )
            .with_headers(**{"content_type": "application/x-www-form-urlencoded"})
            .extract()
            .with_jmespath("body.datas.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseT634().test_start()
